# Generated by Django 6.0.3 on 2026-06-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDayEquipment',
        ),
    ]
