# Generated by Django 6.0.3 on 2026-05-14 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('giveaway', 'Bäsleşik / Giveaway'), ('promotion', 'Aksiýa'), ('gift', 'Sowgat')], default='giveaway', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('banner_url', models.CharField(blank=True, max_length=500)),
                ('bg_gradient', models.CharField(default='from-red-600 to-orange-500', max_length=120)),
                ('prize_title', models.CharField(blank=True, max_length=200)),
                ('prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prize_image', models.CharField(blank=True, max_length=500)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, help_text='Gatnaşmagyň şertleri (her setir aýry şert)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('promo_code', models.CharField(blank=True, max_length=80)),
                ('winners_count', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Garaşylýar'), ('active', 'Işjeň'), ('finished', 'Tamamlandy'), ('cancelled', 'Ýatyryldy')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Garaşylýar'), ('approved', 'Tassyklandy'), ('won', 'Ýeňiji'), ('rejected', 'Ret edildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gifts.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_list', to='gifts.campaign')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_title', models.CharField(blank=True, max_length=200)),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='gifts.campaign')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gifts.campaignparticipation')),
            ],
        ),
    ]
