# Generated by Django 6.0.3 on 2026-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
