# Generated by Django 6.0.3 on 2026-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
