# Generated by Django 6.0.3 on 2026-04-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_contactmessage_reply'),
        ('main', '0003_banner_promo_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='commerce.product'),
        ),
    ]
