# Generated by Django 6.0.3 on 2026-05-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoOrder',
        ),
    ]
