# Generated by Django 6.0.3 on 2026-05-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0003_photoreel_photoreelcomment_photoreelshare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('video', 'video'), ('image', 'image')], default='video', max_length=10)),
                ('cover_url', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='photostudio.photocategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photoreel',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='photostudio.photocollection'),
        ),
    ]
