# Generated by Django 6.0.3 on 2026-06-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0004_photocollection_photoreel_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_image', models.FileField(upload_to='photostudio/images/thumbnails/')),
                ('image', models.FileField(upload_to='photostudio/images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoStudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_image', models.FileField(upload_to='photostudio/videos/thumbnails/')),
                ('video', models.FileField(upload_to='photostudio/videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
