# Generated by Django 6.0.3 on 2026-06-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0005_photostudioimage_photostudiovideo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoreellike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='photocollection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoreel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoreel',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='photoreel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photoreeltag',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='photoreelshare',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='photoreellike',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='photoreelcomment',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='photoreelcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='photoreelcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photoreellike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photoreelshare',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhotoBlog',
        ),
        migrations.DeleteModel(
            name='PhotoMedia',
        ),
        migrations.DeleteModel(
            name='PhotoCategory',
        ),
        migrations.DeleteModel(
            name='PhotoCollection',
        ),
        migrations.DeleteModel(
            name='PhotoReelTag',
        ),
        migrations.DeleteModel(
            name='PhotoReel',
        ),
        migrations.DeleteModel(
            name='PhotoReelComment',
        ),
        migrations.DeleteModel(
            name='PhotoReelLike',
        ),
        migrations.DeleteModel(
            name='PhotoReelShare',
        ),
    ]
