# Generated by Django 6.0.3 on 2026-06-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0006_remove_photomedia_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostudiovideo',
            name='hls_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photostudiovideo',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='photostudiovideo',
            name='hls_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
